### ISSUE TITLE
Figyelmen kívül hagy a plugin pár számlát

### ISSUE THREAD

**Issue by Zylazy** [laszlojakab/homeassistant-dijnet#37]
Több szolgáltatóm is a dijnet-en keresztül küldi a szmlát és bár van ami jól működik, de van olyan ami nem jelenik meg.
Szeritem az utóbbi frissítés óta van ez így, mert korábban ez működött.
![HA - dijnet](https://user-images.githubusercontent.com/8330252/156566609-e4cd8b6f-ac85-4857-b9df-e126e55d06fd.JPG)
Az Áram és Gázszámlák jól megjelennek, de a Hulladék szállításról a számla nem, holott az is még függőben van.
Ahogy a csatolt képeken is látni lehet.
![Web - dijnet](https://user-images.githubusercontent.com/8330252/156566881-3fcb88b2-e563-451f-9109-87cd349f05d4.JPG)

**Comment by laszlojakab** [comment]
Szia, kiadtam egy új béta verziót (0.5.2-beta), amiben vannak hibajavítások. Ki tudnád próbálni ezzel az új verzióval is, hogy jelentkezik-e még a probléma?

**Comment by Zylazy** [comment]
Szia Laci!
Persze, de még nem érhető el.
Amint felajánlja, akkor frissítem és visszajelzek.
Üdv
Laci

Laszlo Jakab ***@***.***> ezt írta (időpont: 2022. márc. 3.,
Cs 22:36):

**Comment by laszlojakab** [comment]
Szia, a függőleges három pont-ra kattintva:

![image](https://user-images.githubusercontent.com/6196882/156844361-2606fb0f-547f-41e4-a3e8-275936ddcbd9.png)

válaszd ki a menüből az újratelepítés menüpontot, a megjelenő ablakban jelöld be, hogy látszanak a béta verziók is, és akkor ott meg kell jelennie ennek a verziónak a legördülő listában.

**Comment by Zylazy** [comment]
Szia Laci! Nagyon köszi!
Rémlett is, hogy valamikor láttam olyat, hogy "béta verziók megjelenítése",
de nem ugrott be, hogy hol van. Köszi a segítséget!
Frissítettem a legutolsó verzióra, a 2-es bétára, de sajnos nem oldotta meg
a problémát. Továbbra is 0 minden. :(
Üdv
Laci

**Comment by laszlojakab** [comment]
Szia Laci (@Zylazy),
Be tudnád kapcsolni a debug szintű naplózást? A configuration.yaml-be kellene ezt belerakni:

```yaml
logger:
  default: error
  logs:
    custom_components.dijnet: debug
```

Ha újraindítottad a Home Assistantot és megjöttek a 0 forintos értékek, akkor mondjuk még 5 perc futás után szeretném elkérni a keletkezett homeassistant.log file tartalmát.
Köszönöm!

**Comment by Zylazy** [comment]
Szia Laci!
Elnézést, hogy csak most reagálok, de sajnos a számlákat már muszáj volt
kiegyenlítem, így nem tudtam tesztelni.
Egyébként a hiba csak vízművek. csatornázási művek és a szemétszállítás
számlákkal jelentkezik.
Telekom, Elmü, Főgáz számlák megjelennek rendesen.
Most egy másik azonosítóval belépve is tapasztaltam a hibát, de ott
csoportos beszedés van beállítva, és nem tudom, hogy az érdekes-e.
Minden esetre ott is nulla szerepel mind három korábban említett
kategóriában és a logokban ez szerepel:
2022-03-10 00:49:06 ERROR (MainThread)
[custom_components.dijnet.controller] Failed to determine invoice state.
State column text: Beszedés alatt
2022-03-10 00:49:06 ERROR (MainThread)
[custom_components.dijnet.controller] Failed to determine invoice state.
State column text: Beszedés alatt
2022-03-10 00:49:06 ERROR (MainThread)
[custom_components.dijnet.controller] Failed to determine invoice state.
State column text: Beszedés alatt
Az én számláimnál nincs csoportos beszedés, de arról egyelőre nem tudok
logot küldeni.
Üdv
Laci

**Comment by Zylazy** [comment]
Szia!
Látom felkerült egy újabb béta verzió. Leteszteltem azt is, de sajnos azzal
sem lett jobb.
Üdv
Laci

Csatolom a kapott logot:

2022-03-13 08:15:59 WARNING (SyncWorker_2) [homeassistant.loader] We found
a custom integration dijnet which has not been tested by Home Assistant.
This component might cause stability problems, be sure to disable it if you
experience issues with Home Assistant
2022-03-13 08:16:19 INFO (MainThread) [custom_components.dijnet.sensor]
Setting up Dijnet sensors.
2022-03-13 08:16:19 DEBUG (MainThread)
[custom_components.dijnet.controller] Updating issuers.
2022-03-13 08:16:19 INFO (MainThread) [custom_components.dijnet.sensor]
Setting up Dijnet sensors.
2022-03-13 08:16:19 DEBUG (MainThread)
[custom_components.dijnet.controller] Updating issuers.
2022-03-13 08:16:20 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Posting login information to
login_check_ajax.
2022-03-13 08:16:20 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Posting login information to
login_check_ajax.
2022-03-13 08:16:21 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting main page.
2022-03-13 08:16:21 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting main page.
2022-03-13 08:16:21 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting szamla_search page.
2022-03-13 08:16:21 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting szamla_search page.
2022-03-13 08:16:22 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting regszolg_new page.
2022-03-13 08:16:22 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting regszolg_new page.
2022-03-13 08:16:22 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting regszolg_list page.
2022-03-13 08:16:22 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting regszolg_list page.
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (Díjbeszedő - .... -
fogyaszto1 víz,csatorna,kuka - ['FCSM Zrt.', 'DFaktorház Zrt.', 'NHKV
Zrt.', 'Fogyasztók', 'FV Zrt.'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (MVM Next - Áram - ....
- fogyaszto1 áram - ['MVM Next - Áram'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (MVM Next - Földgáz -
.... - fogyaszto1 gáz - ['MVM Next - Földgáz'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (Díjbeszedő - .... - fogyaszto1 víz,csatorna,kuka - ['FCSM
Zrt.', 'DFaktorház Zrt.', 'NHKV Zrt.', 'Fogyasztók', 'FV Zrt.'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (MVM Next - Áram - .... - fogyaszto1 áram - ['MVM Next -
Áram'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (MVM Next - Földgáz - .... - fogyaszto1 gáz - ['MVM Next -
Földgáz'])
2022-03-13 08:16:23 INFO (MainThread) [custom_components.dijnet.sensor]
Setting up Dijnet sensors completed.
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (Díjbeszedő - .... -
fogyaszto2 víz,csatorna,kuka - ['NHKV Zrt.', 'FCSM Zrt.', 'FV Zrt.',
'Fogyasztók'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (DRV - .... - fogyaszto3
víz /régi/ - [])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (DRV - .... - fogyaszto3
víz - ['DRV'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (E.ON - .... -
fogyaszto3 áram /régi/ - [])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (E.ON - .... -
fogyaszto3 áram - ['E.ON'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (MVM Next - Földgáz -
.... - fogyaszto3 gáz - ['MVM Next - Földgáz'])
2022-03-13 08:16:23 DEBUG (MainThread)
[custom_components.dijnet.controller] Issuer found (Telekom otthoni,
Telekom-összevont - .... - fogyaszto2 telekom - ['Telekom otthoni,
Telekom-összevont'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (Díjbeszedő - .... - fogyaszto2 víz,csatorna,kuka - ['NHKV
Zrt.', 'FCSM Zrt.', 'FV Zrt.', 'Fogyasztók'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (DRV - .... - fogyaszto3 víz /régi/ - [])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (DRV - .... - fogyaszto3 víz - ['DRV'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (E.ON - .... - fogyaszto3 áram /régi/ - [])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (E.ON - .... - fogyaszto3 áram - ['E.ON'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (MVM Next - Földgáz - .... - fogyaszto3 gáz - ['MVM Next -
Földgáz'])
2022-03-13 08:16:23 DEBUG (MainThread) [custom_components.dijnet.sensor]
Sensor added (Telekom otthoni, Telekom-összevont - .... - fogyaszto2
telekom - ['Telekom otthoni, Telekom-összevont'])
2022-03-13 08:16:23 INFO (MainThread) [custom_components.dijnet.sensor]
Setting up Dijnet sensors completed.
2022-03-13 08:17:00 DEBUG (MainThread)
[custom_components.dijnet.controller] Updating invoices.
2022-03-13 08:17:00 DEBUG (MainThread)
[custom_components.dijnet.controller] Loading registry from
".dijnet_registry.yaml"
2022-03-13 08:17:00 DEBUG (MainThread)
[custom_components.dijnet.controller] Loading invoices from
".dijnet_paid_invoices.yaml"
2022-03-13 08:17:01 DEBUG (MainThread)
[custom_components.dijnet.controller] Updating invoices.
2022-03-13 08:17:01 DEBUG (MainThread)
[custom_components.dijnet.controller] Loading registry from
".dijnet_registry.yaml"
2022-03-13 08:17:01 DEBUG (MainThread)
[custom_components.dijnet.controller] Loading invoices from
".dijnet_paid_invoices.yaml"
2022-03-13 08:17:05 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Posting login information to
login_check_ajax.
2022-03-13 08:17:05 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Posting login information to
login_check_ajax.
2022-03-13 08:17:07 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting main page.
2022-03-13 08:17:07 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting main page.
2022-03-13 08:17:08 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting szamla_search page.
2022-03-13 08:17:08 DEBUG (MainThread)
[custom_components.dijnet.dijnet_session] Getting szamla_search page.
2022-03-13 08:17:29 WARNING (MainThread) [homeassistant.helpers.entity]
Update of sensor.dijnet_fogyaszto1_csatorna is taking over 10 seconds
2022-03-13 08:17:29 WARNING (MainThread) [homeassistant.helpers.entity]
Update of sensor.dijnet_nhkv_zrt_fizetendo_osszeg_2 is taking over 10
seconds
2022-03-13 08:17:29 ERROR (MainThread) [homeassistant.helpers.entity]
Update for sensor.dijnet_fogyaszto1_csatorna fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type:
ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in
create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in
_create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521,
in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 734,
in async_device_update
    await task
  File "/config/custom_components/dijnet/sensor.py", line 121, in
async_update
    invoices = [invoice for invoice in await
self._controller.get_unpaid_invoices() if invoice.display_name ==
self._invoice_issuer.display_name and invoice.provider == self._provider]
  File "/config/custom_components/dijnet/controller.py", line 343, in
get_unpaid_invoices
    await self.update_invoices()
  File "/config/custom_components/dijnet/controller.py", line 437, in
update_invoices
    await session.get_invoice_search_page()
  File "/config/custom_components/dijnet/dijnet_session.py", line 159, in
get_invoice_search_page
    async with
self._session.get(f'{ROOT_URL}/ekonto/control/szamla_search') as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line
1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line
535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host
www.dijnet.hu:443 ssl:default [None]
2022-03-13 08:17:30 ERROR (MainThread) [homeassistant.helpers.entity]
Update for sensor.dijnet_nhkv_zrt_fizetendo_osszeg_2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type:
ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in
create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in
_create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521,
in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 734,
in async_device_update
    await task
  File "/config/custom_components/dijnet/sensor.py", line 121, in
async_update
    invoices = [invoice for invoice in await
self._controller.get_unpaid_invoices() if invoice.display_name ==
self._invoice_issuer.display_name and invoice.provider == self._provider]
  File "/config/custom_components/dijnet/controller.py", line 343, in
get_unpaid_invoices
    await self.update_invoices()
  File "/config/custom_components/dijnet/controller.py", line 437, in
update_invoices
    await session.get_invoice_search_page()
  File "/config/custom_components/dijnet/dijnet_session.py", line 159, in
get_invoice_search_page
    async with
self._session.get(f'{ROOT_URL}/ekonto/control/szamla_search') as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line
1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line
535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line
992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host
www.dijnet.hu:443 ssl:default [None]

**Comment by laszlojakab** [comment]
Szia Laci @Zylazy,
A 'Beszedés alatt' kezelése a legutóbb kiadott béta verzióban lett megoldva. A `Cannot connect to host
[www.dijnet.hu:443](http://www.dijnet.hu:443/) ssl:default` hiba jellemzően valamilyen ideglenes probléma szokott lenni. Esetleg azóta nem jelentek meg az összegek?

**Comment by Zylazy** [comment]
Szia!
Nem, nekem soha nem volt beállítva csoportos beszedés. Ez csak most
ideiglenesen lett beállítva.
A javítás akkor jó lett, mert azt az error-t nem látom, de az összegek most
se jelennek meg. De csak a víz, csatorna, kuka számláknál jelentkezik.
Áram, gáz, telekom számlákkal minden rendben.
Laci

Laszlo Jakab ***@***.***> ezt írta (időpont: 2022. márc. 13.,
V 20:56):

**Comment by laszlojakab** [comment]
Tehát, csak, hogy tisztán lássak, most vannak befizetetlen számláid, és mindenütt 0 forint jelenik meg? Illetve most mi van a naplóban (ha van fizetendő számlád)?

**Comment by Zylazy** [comment]
Most csak olyan van, ami nem az enyém csak be lett állítva hogy teszteljem,
ami igaz befizetetlen számla, de beszedéses. De amint lesz ismét saját
akkor majd tudom tesztelni rendesen.

Laszlo Jakab ***@***.***> ezt írta (időpont: 2022. márc. 13.,
V 22:10):

**Comment by Zylazy** [comment]
Szia Laci!
Jöttek újabb számlák és megjelentek rendesen most már.
Köszi a javítást!
Laci

Zyla . ***@***.***> ezt írta (időpont: 2022. márc. 13., V 22:13):
