### ISSUE TITLE
A Díjnet szenzorok elérhetetlenek

### ISSUE THREAD

**Issue by KixMan28** [laszlojakab/homeassistant-dijnet#82]
A HA 2024.10-es verzióban a Díjnet szenzorok elérhetetlenné váltak. 

A HA logban a következő látszik:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
integration: Sensor (documentation, issues)
First occurred: 12:04:47 (2 occurrences)
Last logged: 12:04:47

Error while setting up dijnet platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/dijnet/sensor.py", line 78, in async_setup_entry
    for registered_invoice_issuer in await controller.get_issuers():
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dijnet/controller.py", line 386, in get_issuers
    await self.update_registered_issuers()
  File "/config/custom_components/dijnet/controller.py", line 420, in update_registered_issuers
    issuer_name = row.children("td:nth-child(1)").text()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyquery/pyquery.py", line 1156, in text
    return ' '.join(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyquery/pyquery.py", line 1158, in <genexpr>
    extract_text(tag, **kwargs) for tag in self
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyquery/text.py", line 100, in extract_text
    a = extract_text_array(dom, squash_artifical_nl=squash_space)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyquery/text.py", line 82, in extract_text_array
    if dom.text is not None:
       ^^^^^^^^
  File "src/lxml/etree.pyx", line 1059, in lxml.etree._Element.text.__get__
  File "src/lxml/apihelpers.pxi", line 708, in lxml.etree._collectText
  File "src/lxml/apihelpers.pxi", line 1512, in lxml.etree.funicode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 25: invalid start byte
```

**Comment by HyGy** [comment]
Detected that custom integration 'dijnet' calls async_forward_entry_setup for integration, dijnet with title: Dijnet (username) and entry_id: 624c13c266be451cab8eab8472913c05, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/dijnet/__init__.py, line 68: hass.async_create_task(, please create a bug report at https://github.com/laszlojakab/homeassistant-dijnet/issues

Talán ez is ugyan az a hiba. De elérhetetlenné vált a díjnet integráció nekem is.

**Comment by laszlojakab** [comment]
A warningokkal egyelőre nincs sajnos most szabad időm foglalkozni, később lesznek megoldva, a `utf-8`-as hibára felraktam egy javítást, kérlek próbáljátok ki, megoldja-e nektek is a problémát: https://github.com/laszlojakab/homeassistant-dijnet/tree/fix/reencode-responses-to-utf-8

**Comment by notovi** [comment]
Javítás után:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte

**Comment by cyberfly79** [comment]
Javítás után:
HA core dockerben 2024.10.2

2024-10-15 10:31:44.097 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up dijnet platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/dijnet/sensor.py", line 78, in async_setup_entry
    for registered_invoice_issuer in await controller.get_issuers():
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dijnet/controller.py", line 386, in get_issuers
    await self.update_registered_issuers()
  File "/config/custom_components/dijnet/controller.py", line 401, in update_registered_issuers
    if not await session.post_login(self._username, self._password):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dijnet/dijnet_session.py", line 248, in post_login
    json = await response.json(content_type='text/plain')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 405, message='Attempt to decode JSON with unexpected mimetype: text/html',
url='https://www.dijnet.hu/ekonto/login/login_check_ajax'

**Comment by laszlojakab** [comment]
fixed by #83
